### ISSUE TITLE
Wahl auswählen, für die Statements angezeigt werden

### ISSUE THREAD

**Issue by kmille** [Parteiduell/data#2]
es stehen ja dieses Jahr einige Landtagswahl + Bundestagswahl an:
https://www.bundesrat.de/DE/termine/wahl-termine/wahl-termine.html
Wäre cool (ich weiß nicht obs aktuell schon geht), wenn man die Datenquellen sehen könnte und eine davon auswählen könnte und dann nur Statements aus einer bestimmten Wahl bekommt (wie z. B. der der Bundestagswahl 2021).

**Comment by gruselhaus** [comment]
<img width="1486" alt="Bildschirmfoto 2021-01-14 um 17 51 51" src="https://user-images.githubusercontent.com/33380107/104622172-35ee7a00-5691-11eb-9a9a-4b158c1afd23.png">

@kmille du kannst in den Einstellungen die Datenquellen auswählen.

Die Daten für dieses Jahr haben wir noch nicht.

**Comment by kmille** [comment]
was muss man den tun um an die Einstellungen zu kommen?

**Comment by gruselhaus** [comment]
<img width="1486" alt="104622172-35ee7a00-5691-11eb-9a9a-4b158c1afd23" src="https://user-images.githubusercontent.com/33380107/104639404-abfddb80-56a7-11eb-8222-b5a03bd85f6e.png">
Sollten wir eventuell mal ein bisschen präsenter positionieren....

**Comment by kmille** [comment]
oh - total übersehen - sry :D
